#!/usr/bin/env bash
# Measures what Lemnos costs a binary on small targets and compares it with
# testing/size/baseline.txt:
#   - bare-metal firmware images (flash bytes) using the no_std drivers, for a
#     Cortex-M4F and an FPU-less RISC-V core, with and without `float`, and
#     the four drivers through the device-model traits (`device-static`), as
#     `dyn` devices (`device`) and in a `lemnos-lite` table (`lite`);
#   - stripped, size-optimized Linux binaries using the facade, plus an empty
#     `main` built the same way for reference;
#   - stripped Linux binaries reading three sensors without the runtime,
#     through the drivers' own APIs and through a `lemnos-lite` table.
# There are no absolute budgets: the check fails when an image grows by more
# than max(64 bytes, 1%) over the baseline. Shrinking is always fine. Linux
# binaries go through the system linker and libc, which differ between hosts,
# so they get 5% before failing; firmware links with rust-lld and is exact.
#
#   ./scripts/check-sizes.sh            measure and compare
#   ./scripts/check-sizes.sh --update   measure and rewrite the baseline
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
size_dir="$root_dir/testing/size"
baseline="$size_dir/baseline.txt"
target_dir="${CARGO_TARGET_DIR:-$root_dir/target}/size"
update=false
[[ "${1:-}" == "--update" ]] && update=true

sysroot="$(rustc --print sysroot)"
llvm_size="$(ls "$sysroot"/lib/rustlib/*/bin/llvm-size 2>/dev/null | head -1 || true)"
if [[ -z "$llvm_size" ]]; then
  rustup component add llvm-tools >/dev/null 2>&1 || true
  llvm_size="$(ls "$sysroot"/lib/rustlib/*/bin/llvm-size 2>/dev/null | head -1 || true)"
fi
[[ -n "$llvm_size" ]] || { echo "llvm-size not found (rustup component add llvm-tools)" >&2; exit 1; }

results="$(mktemp)"
trap 'rm -f "$results"' EXIT

# Firmware: flash = .text + .rodata + .data.
fw_targets=(thumbv7em-none-eabihf riscv32imac-unknown-none-elf)
fw_images=(regs vcm ina2xx bmm150 bmi088 vcm,ina2xx,bmm150,bmi088 vcm,ina2xx,bmm150,bmi088,float device-static device lite)
for target in "${fw_targets[@]}"; do
  rustup target add "$target" >/dev/null 2>&1 || true
  for image in "${fw_images[@]}"; do
    RUSTFLAGS="-C link-arg=-T$size_dir/firmware/link.x" cargo build -q --release \
      --manifest-path "$size_dir/firmware/Cargo.toml" --target-dir "$target_dir/firmware" \
      --target "$target" --features "$image"
    bytes="$("$llvm_size" -A "$target_dir/firmware/$target/release/lemnos-size-firmware" |
      awk '$1==".text"||$1==".rodata"||$1==".data"{s+=$2} END{print s+0}')"
    echo "firmware/$target/$image $bytes" >>"$results"
  done
done

# Linux: stripped file size of the facade consumer, per feature set.
lite="linux,lemnos/linux-gpio,lemnos/linux-gpio-cdev,lemnos/linux-pwm,lemnos/linux-i2c,lemnos/linux-spi,lemnos/linux-hotplug"
linux_images=("facade|" "linux-lite|$lite" "linux-lite-builtin|$lite,builtin")
host="$(rustc -vV | awk '/^host:/{print $2}')"
for entry in "${linux_images[@]}"; do
  name="${entry%%|*}"; features="${entry#*|}"
  cargo build -q --release --manifest-path "$size_dir/linux/Cargo.toml" \
    --target-dir "$target_dir/linux-$name" ${features:+--features "$features"}
  echo "linux/$host/$name $(stat -c %s "$target_dir/linux-$name/release/lemnos-size-linux")" >>"$results"
done

# Linux without the runtime: three sensors on /dev/i2c-N, through each
# driver's API and through a lemnos-lite table.
for entry in "sensors|" "sensors-lite|lite"; do
  name="${entry%%|*}"; features="${entry#*|}"
  cargo build -q --release --manifest-path "$size_dir/linux-sensors/Cargo.toml" \
    --target-dir "$target_dir/linux-$name" ${features:+--features "$features"}
  echo "linux/$host/$name $(stat -c %s "$target_dir/linux-$name/release/lemnos-size-linux-sensors")" >>"$results"
done

if $update; then
  { echo "# Generated by scripts/check-sizes.sh --update; bytes per image."; sort "$results"; } >"$baseline"
  echo "Baseline updated: $baseline"
  cat "$baseline"
  exit 0
fi

status=0
printf "%-62s %10s %10s %8s\n" image baseline now change
while read -r image bytes; do
  base="$(awk -v k="$image" '$1==k{print $2}' "$baseline" 2>/dev/null || true)"
  if [[ -z "$base" ]]; then
    printf "%-62s %10s %10d %8s\n" "$image" "-" "$bytes" "new"
    continue
  fi
  delta=$((bytes - base))
  percent=1
  [[ "$image" == linux/* ]] && percent=5
  allowed=$(( base * percent / 100 > 64 ? base * percent / 100 : 64 ))
  mark=""
  if (( delta > allowed )); then mark="  <-- grew"; status=1; fi
  printf "%-62s %10d %10d %+8d%s\n" "$image" "$base" "$bytes" "$delta" "$mark"
done < <(sort "$results")

if (( status != 0 )); then
  echo "Some images grew beyond noise. If intended, run ./scripts/check-sizes.sh --update and commit the baseline." >&2
fi
exit "$status"
